/* generated by /home/chen/sel4/charvis/tools/seL4/elfloader-tool/../cmake-tool/helpers/platform_sift.py BEGIN */
int num_memory_regions = 1;

struct memory_region {
    size_t start;
    size_t end;
} memory_region[1] = {
	{ .start = 1610612736, .end = 3221225472 },
};
/* generated by /home/chen/sel4/charvis/tools/seL4/elfloader-tool/../cmake-tool/helpers/platform_sift.py END */
